library(Capr)

# Generated by jsonToCapr()
# Source JSON: /Users/michaelconlin/hades/cohort_arbs_outcome.json

# --- concept sets ---
csRenalCellCarcinoma0 <- cs(
  descendants(45765451, 45773365, 37116954),
  198985,
  name = "renal cell carcinoma",
  id = 0
)

attritionObj <- attrition(
  expressionLimit = "All"
)

# --- cohort ---
outcomeCohortDef <- cohort(
  entry = entry(
    conditionOccurrence(csRenalCellCarcinoma0, firstOccurrence()),
    observationWindow = continuousObservation(priorDays = 0L, postDays = 0L),
    primaryCriteriaLimit = "All",
    qualifiedLimit = "First"
  ),
  attrition = attritionObj,
  exit = exit(
    endStrategy = observationExit()
  ),
  era = era(eraDays = 30L)
)
