# Analysis Code
# TCO and negative controls are already in the cohort table

# ---------------------------------------------------------------------------
# OPTIMIZED VERSION
# Based on create_cohort_method_data.R. This copy incorporates changes made
# after the VINCI DBA team terminated the covariate-build query generated by
# getDbCohortMethodData() on 2026-08-13 (see queryErrorEmail.txt) for using
# 605 GB of TempDB over a ~3 hour open transaction. The killed query itself
# is saved in corhotMethodGenerated.sql - it was the MeasurementRangeGroup
# covariate (analysis id 712), short-term (30-day) window.
#
# Every change below is marked with an "OPTIMIZATION:" comment explaining
# what changed and why. Nothing outside those marked blocks was altered.
# ---------------------------------------------------------------------------

# be sure to set the env variables and database connection details first
source()

# Define the covariates (by eliminating the target and comparator concept_id s)
library(CohortMethod)

# Conncection, Schema, etc

# define the treatment and comparator concept_ids for elimination from covariates
arbs <- c(
  1308842,
  1317640,
  1346686,
  1347384,
  1351557,
  1367500,
  40226742,
  40235485
)

non_arbs <- c(21601783, 21601801, 21601744, 21601461, 21601665)

# Question - do I need to also eliminate the outcome (RCCA) and exclusion criteria from the
# covariates

# NOTE: addDescendantsToExclude = TRUE expands this concept list via
# concept_ancestor before it's used in the covariate SQL's exclusion filter
# (see corhotMethodGenerated.sql, "NOT IN (SELECT id FROM #id_set_1)"). If
# the resulting exclusion set is large, ask VINCI DBA to confirm that
# temp table is indexed - an unindexed NOT IN against a large set can force
# a nested-loop anti-join across the full measurement/condition/drug tables
# instead of a cheap hash lookup, adding to the TempDB pressure seen in
# queryErrorEmail.txt.
covar_settings <- createDefaultCovariateSettings(
  excludedCovariateConceptIds = c(arbs, non_arbs),
  addDescendantsToExclude = TRUE
)

# OPTIMIZATION 1: Keep only the long-term (365-day) covariate window.
# createDefaultCovariateSettings() computes short (30d), medium (180d), AND
# long (365d) term covariates for every domain by default - that's roughly
# 3x the full joins against condition_occurrence/drug_exposure/measurement
# etc. compared to a single window. This was a major contributor to the
# TempDB blowup. Long-term-only was chosen as the best balance of cost vs.
# capturing patient history for the PS model.
term_flags_to_disable <- grepl("MediumTerm|ShortTerm", names(covar_settings)) &
  vapply(covar_settings, isTRUE, logical(1))
covar_settings[term_flags_to_disable] <- FALSE

# OPTIMIZATION 2: Disable MeasurementRangeGroup covariates entirely.
# This is the exact covariate analysis (id 712: buckets each lab value as
# below/within/above its reference range) whose generated SQL is saved in
# corhotMethodGenerated.sql and was killed by VINCI DBA for excessive
# TempDB usage. Plain Measurement covariates (presence/value) remain
# enabled via OPTIMIZATION 1 above (long-term window only).
range_group_flags <- grepl("MeasurementRangeGroup", names(covar_settings)) &
  vapply(covar_settings, isTRUE, logical(1))
covar_settings[range_group_flags] <- FALSE

# Load the Data for analysis
#ToDo review this function below for consistancy with the schemas, tables, etc.

# OPTIMIZATION 3: firstExposureOnly = TRUE and removeDuplicateSubjects =
# "keep first" (changed from FALSE/FALSE). If a subject can have more than
# one row in the cohort table (multiple exposure episodes), each row gets
# its own covariate lookup window, multiplying the join cost against
# condition/drug/measurement tables by the average number of episodes per
# subject. This is a safety net in case the "already deduplicated" cohort
# table assumption (see comment at top of file) doesn't hold for every
# subject. This must stay consistent with the same settings used in
# createStudyPopulation() below.
cmData <- getDbCohortMethodData(
  connectionDetails = connectionDetails,
  cdmDatabaseSchema = cdmDatabaseSchema,
  oracleTempSchema = NULL,
  targetId = 1,
  comparatorId = 2,
  outcomeIds = 3,
  studyStartDate = "",
  studyEndDate = "",
  exposureDatabaseSchema = cohortDbSchema,
  exposureTable = cohortTable,
  outcomeDatabaseSchema = cohortDbSchema,
  outcomeTable = cohortTable,
  cdmVersion = cdmVersion,
  firstExposureOnly = TRUE,
  removeDuplicateSubjects = "keep first",
  restrictToCommonPeriod = FALSE,
  washoutPeriod = 0,
  covariateSettings = covar_settings
)

# RECOMMENDATION: before running this against the full cohort, consider a
# small pilot (e.g., a subject subsample, or covariateSettings restricted to
# one domain at a time) to sanity-check runtime/TempDB usage against this
# database, given the prior termination. Check the estimated query plan as
# VINCI DBA suggested in queryErrorEmail.txt before rerunning at full scale.

# save the cohort data
saveCohortMethodData(cmData, "arb_study_data.zip")

# to load the data, use loadCohortMethodData() function

summary(cmData)

# Now create the study population
# review all these
# OPTIMIZATION 3 (cont'd): firstExposureOnly and removeDuplicateSubjects here
# are kept consistent with the values used in getDbCohortMethodData() above
# (TRUE / "keep first"). This also resolves the "or should this be FALSE"
# question that was previously here - "keep all" (which allowed multiple
# rows per subject) was the mismatch driving up covariate cost upstream.
studyPop <- createStudyPopulation(
  cohortMethodData = cmData,
  outcomeId = 3,
  firstExposureOnly = TRUE,
  restrictToCommonPeriod = FALSE,
  washoutPeriod = 0,
  removeDuplicateSubjects = "keep first",
  removeSubjectsWithPriorOutcome = TRUE,
  minDaysAtRisk = 1,
  riskWindowStart = 1,
  startAnchor = "cohort start",
  riskWindowEnd = 0,
  endAnchor = "cohort end"
)

# Note that we've set firstExposureOnly and removeDuplicateSubjects to TRUE /
# "keep first" (see OPTIMIZATION 3 above) rather than FALSE, because we can no
# longer assume the cohort definitions alone guarantee one row per subject -
# doing so protects against the TempDB blowup described in queryErrorEmail.txt.
# We specify the outcome ID we will use, and that people with outcomes prior to the
# risk window start date will be removed. The risk window is defined as
# starting on the day after the cohort start date
# (riskWindowStart = 1 and startAnchor = "cohort start"),
# and the risk windows ends when the cohort exposure ends
# (riskWindowEnd = 0 and endAnchor = "cohort end"),
# which was defined as the end of exposure in the cohort definition.
# Note that the risk windows are automatically truncated at the end of
# observation or the study end date. We also remove subjects who have
# no time at risk. To see how many people are left in the study population
# we can always use the getAttritionTable function:

getAttritionTable(studyPop)

# Now create the propensity scores
#ToDo - figure out the best setting for creating the propensity scores, type, optimization, etc

ps <- createPs(cohortMethodData = cmData, population = studyPop)
